### ISSUE TITLE
Can not run BlazorApp1.Client

### ISSUE THREAD

**Issue by RightFS** [mguinness/IdentityManagerBlazorUnited#3]
Hi, thanks for your opensource of this manager UI, I have some trouble here.

```
>dotnet run
WasmAppHost --use-staticwebassets --runtime-config /Users/right/Development/ylpay/IdentityManagerBlazorUnited/BlazorApp1.Client/bin/Debug/net8.0/BlazorApp1.Client.runtimeconfig.json
Error: Cannot find runtime config at /Users/right/Development/ylpay/IdentityManagerBlazorUnited/BlazorApp1.Client/bin/Debug/net8.0/BlazorApp1.Client.runtimeconfig.json
```

after rename `BlazorApp1.Client.staticwebassets.runtime.json` to  `BlazorApp1.Client.runtimeconfig.json`:
```
>dotnet run
WasmAppHost --use-staticwebassets --runtime-config /Users/right/Development/ylpay/IdentityManagerBlazorUnited/BlazorApp1.Client/bin/Debug/net8.0/BlazorApp1.Client.runtimeconfig.json
Error: Failed to deserialize /Users/right/Development/ylpay/IdentityManagerBlazorUnited/BlazorApp1.Client/bin/Debug/net8.0/BlazorApp1.Client.runtimeconfig.json - rconfig.RuntimeOptions
```

Another question is why use wasm project instead of js(react vue) or normal razor page, the wasm project is too slow to load for me. Is it possible that I can 'conver' this project to server render razor page?

**Comment by mguinness** [comment]
> I have some trouble here

Did you have the client project set as the start-up project instead of the server project?

> Another question is why use wasm project instead of js(react vue)

An earlier iteration of this project at [IdentityManagerUI](https://github.com/mguinness/IdentityManagerUI) uses a JS framework

**Comment by RightFS** [comment]
Useless reply but thanks, I'm going to stay away from the stupid wasm project.
